---
slug: :mikutter_extract_media
depends:
  mikutter: 3.9.0
  plugin:
    - score
version: '1.0'
author: '@cobodo@mstdn.kanagu.info'
name: mikutter_extract_media
description: 抽出タブの絞り込み条件に「メディアを含む」を追加するmikutterプラグイン
